Repository mdblp/blip, pull requests merged in 2019-11, with the labels that each got.

#120 PT-719 Add parameters translations
  .gitignore
  CHANGELOG.md
  README.md
  app/core/language.js
  artifact.sh
  locales/de/parameter.json
  locales/de/translation.json
  locales/en/parameter.json
  locales/fr/parameter.json
  package.json
Labels: translation

#128 PT-774 Fix problems with translations in blip
  CHANGELOG.md
  app/core/constants.js
  app/pages/signup/signup.js
Labels: bug

#125 PT-771 Analytics/metrics for Blip/Front usage
  CHANGELOG.md
  app/core/api.js
  app/pages/login/login.js
  app/pages/passwordreset/request.js
  app/routes.js
  buildconfig.js
  config.server.js
  config/env.docker.sh
  config/local.sh
  dblp-webpack-html-plugin.js
  index.ejs
  package.json
  server.js
Labels: WIP, enhancement
