Repository mdblp/blip, pull requests merged in 2021-05, with the labels that each got.

#514 Switch back to dblp branch
  .github/workflows/codeql-analysis.yml
  Jenkinsfile
  cloudfront-dist/deployment/preview.env
  package-lock.json
  package.json
Labels: teams

#534 YLP-741 Fix temp basal as loop mode OFF
  packages/tideline/js/tidelinedata.js
Labels: teams

#543 Fix compile warning
  packages/tideline/plugins/blip/basics/components/sitechange/Selector.js
Labels: teams

#542 Fix allow to cancel invitations
  packages/yourloops/lib/notifications/api.ts
  packages/yourloops/lib/notifications/models.ts
  packages/yourloops/pages/hcp/team-members-table.tsx
  packages/yourloops/pages/notifications/notification.tsx
Labels: high, teams

#541 Fix send an email when remove an HCP team member
  packages/yourloops/lib/team/api.ts
  packages/yourloops/lib/team/hook.tsx
  packages/yourloops/lib/team/models.ts
  packages/yourloops/test/lib/team/hook.test.tsx
  packages/yourloops/test/pages/hcp/teams-page.test.tsx
Labels: high, teams

#519 Update changelog with Blip v2 features
  CHANGELOG.md
  package-lock.json
  package.json
  packages/blip/package.json
  packages/tideline/package.json
  packages/viz/package.json
  packages/yourloops/package.json
Labels: merge-last, teams
