Repository mdblp/blip, pull requests merged in 2022-03, with the labels that each got.

#749 YLP-1285 Avg daily carbs in PDF to use rescue carbs and meal
  CHANGELOG.md
  packages/viz/src/modules/print/BasicsPrintView.js
  packages/viz/test/modules/print/BasicsPrintView.test.js
Labels: 2.0.6

#741 YLP-1304 Bump SOUP & clean-up & eng fixes
  .eslintrc.js
  .vscode/settings.json
  CHANGELOG.md
  package-lock.json
  package.json
  packages/blip/app/components/chart/daily.js
  packages/blip/app/components/chart/header.js
  packages/blip/app/components/chart/trends.js
  packages/blip/app/components/patient-data.js
  packages/blip/package.json
  packages/blip/test/unit/components/chart/daily.test.js
  packages/blip/test/unit/components/chart/trends.test.js
  packages/tideline/js/tidelinedata.js
  packages/tideline/plugins/blip/basics/components/day/hover/InfusionHoverDisplay.js
  packages/viz/package.json
  packages/viz/src/components/common/tooltips/Tooltip.js
  packages/viz/src/components/daily/reservoirtooltip/ReservoirTooltip.js
  packages/yourloops/app/app.tsx
  packages/yourloops/app/index.tsx
  packages/yourloops/components/buttons/icon-action.tsx
  packages/yourloops/components/buttons/progress-icon-button-wrapper.tsx
  packages/yourloops/components/utils/password.tsx
  packages/yourloops/lib/auth/api.ts
  packages/yourloops/lib/axios.ts
  packages/yourloops/pages/hcp/certify-account-page.tsx
  packages/yourloops/pages/hcp/patients/table.tsx
  packages/yourloops/services/http.ts
  packages/yourloops/test/components/password-strength-meter.test.tsx
  packages/yourloops/test/services/http.test.ts
  packages/yourloops/webpack.config.blip.js
  packages/yourloops/webpack.config.js
Labels: 2.0.6

#703 v2.0.6
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
  packages/blip/package.json
  packages/tideline/package.json
  packages/viz/package.json
  packages/yourloops/package.json
Labels: 2.0.6

#753 YLP-1312 Fix data load ranges
  CHANGELOG.md
  packages/blip/app/components/chart/trends.js
  packages/blip/app/components/patient-data.js
  packages/blip/app/core/api-utils.js
  packages/blip/app/core/lib/partial-data-load.js
  packages/blip/test/import-tests.js
  packages/blip/test/unit/lib/partial-data-load.test.js
  packages/tideline/js/tidelinedata.js
  packages/yourloops/components/patient-data.tsx
  packages/yourloops/lib/data/api.ts
  packages/yourloops/lib/data/blip-api.ts
Labels: 2.0.7

#754 YLP-1313 Join wizard and bolus may fail
  CHANGELOG.md
  packages/tideline/js/tidelinedata.js
  packages/tideline/plugins/nurseshark/index.js
  packages/tideline/test/nurseshark.test.js
  packages/tideline/test/tidelinedata.test.js
Labels: 2.0.7

#756 YLP-1319 Switch-roles dialogs CSS not consistent with other dialogs
  CHANGELOG.md
  packages/yourloops/components/switch-role/consent-dialog.tsx
  packages/yourloops/components/switch-role/consequences-dialog.tsx
  packages/yourloops/components/switch-role/index.tsx
  packages/yourloops/components/switch-role/profession-dialog.tsx
Labels: 2.0.7

#755 YLP-1256 Split profile page into several components
  CHANGELOG.md
  packages/yourloops/components/header-bars/primary.tsx
  packages/yourloops/components/password/password.tsx
  packages/yourloops/lib/auth/user.ts
  packages/yourloops/pages/profile/credentials-form.tsx
  packages/yourloops/pages/profile/patient-form.tsx
  packages/yourloops/pages/profile/personal-info-form.tsx
  packages/yourloops/pages/profile/preferences-form.tsx
  packages/yourloops/pages/profile/profile.tsx
  packages/yourloops/pages/profile/secondary-bar.tsx
  packages/yourloops/test/lib/auth/user.test.tsx
Labels: 2.0.7

#769 Babel optimisation
  babel.config.json
  package-lock.json
  package.json
Labels: 3.0.0
